jobs:
  build-and-test:
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g"
    name: Build and run tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout current develop branch
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v3.11.0
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Run unit/instrumentation tests and coverage generation
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86_64
        disable-animations: true
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio
          -no-boot-anim
        force-avd-creation: false
        script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.notAnnotation=androidx.test.filters.FlakyTest,androidx.test.filters.LargeTest
          jacocoTestReport --stacktrace
        target: google_apis
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: SonarCloud static code and coverage analysis
      run: ./gradlew sonarqube -Dsonar.login="$SONAR_TOKEN"
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
